system:
  debug: true
  version: v1.0.0
  daemons: false
  timezone: 8
web-service:
  port: "19900"
  cors: true
  static-dir:
  - url: /web
    dir: resource/html/spa
  - url: /manager
    dir: resource/html/manager
log:
  daemons:
    dir: storage/runtime/log
    filename: daemons.log
  zap:
    compress: true
    encoder-type: CONSOLE
    filename: storage/runtime/logs/app.log
    in-console: true
    level: info
    max-age: 180
    max-backups: 180
    max-size: 1024
rezip:
  out-dir: storage/runtime/rezip
file-manager:
  port: "19901"
  dir: storage/runtime/file-manager
message-board:
  dir: storage/runtime/message-board
checking-in:
  tmp-dir: storage/runtime/checking-in
