//go:build never
// +build never

package driver
















































































































































}	}		t.Fatalf("DefaultUUIDWithHyphen = %v, want false", config.DefaultUUIDWithHyphen)	if config.DefaultUUIDWithHyphen == nil || *config.DefaultUUIDWithHyphen {	}		t.Fatalf("DefaultUUIDVersion = %d, want 7", config.DefaultUUIDVersion)	if config.DefaultUUIDVersion != 7 {	config := db.GetConfig()	defer db.Close()	}		t.Fatalf("Open DB error = %v", err)	if err != nil {	)		kernal.UUIDWithHyphen(false),		kernal.UUIDVersion(7),	db, err := New.DB(database, table,	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(database, table)) })	_ = os.RemoveAll(filepath.Join(database, table))	table := "driver_attrs"	database := "demo"func TestDriver_SetAttrs(t *testing.T) {}	}		t.Fatalf("Rollback error = %v", err)	if err = tx.Rollback(); err != nil {	}		t.Fatalf("tx.Get = (%s,%v), want (v2,true)", string(value), ok)	if !ok || string(value) != "v2" {	}		t.Fatalf("tx.Get error = %v", err)	if err != nil {	value, ok, err := tx.Get("k")	}		t.Fatalf("Put(v2) error = %v", err)	if err = db.Put("k", []byte("v2")); err != nil {	}		t.Fatalf("BeginTxWithOptions error = %v", err)	if err != nil {	tx, err := db.BeginTxWithOptions(TxOptions{Isolation: TxIsolationReadCommitted})	}		t.Fatalf("Put(v1) error = %v", err)	if err = db.Put("k", []byte("v1")); err != nil {	defer db.Close()	}		t.Fatalf("Open DB error = %v", err)	if err != nil {	db, err := New.DB(database, table)	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(database, table)) })	_ = os.RemoveAll(filepath.Join(database, table))	table := "driver_tx_options"	database := "demo"func TestDriver_TxOptionsReadCommitted(t *testing.T) {}	}		t.Fatalf("error code = %s, want %s", dErr.Code, ErrorCodeNotFound)	if dErr.Code != ErrorCodeNotFound {	}		t.Fatalf("error type = %T, want *DriverError", err)	if !errors.As(err, &dErr) {	var dErr *DriverError	}		t.Fatalf("Delete(missing) error=nil, want not nil")	if err == nil {	err = db.Delete("missing-key")	defer db.Close()	}		t.Fatalf("Open DB error = %v", err)	if err != nil {	db, err := New.DB(database, table)	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(database, table)) })	_ = os.RemoveAll(filepath.Join(database, table))	table := "driver_error_model"	database := "demo"func TestDriver_ErrorModel(t *testing.T) {}	}		t.Fatalf("id mismatch = %v vs %v", found["id"], row["id"])	if found["id"] != row["id"] {	}		t.Fatalf("FindOne ok=false, want true")	if !ok {	}		t.Fatalf("FindOne error = %v", err)	if err != nil {	found, ok, err := db.FindOne(QueryCondition{Field: "username", Operator: QueryOpEQ, Value: "driver_alice"})	}		t.Fatalf("Commit error = %v", err)	if err = tx.Commit(); err != nil {	}		t.Fatalf("InsertRow(tx) error = %v", err)	if err != nil {	row, err := tx.InsertRow(Row{"username": "driver_alice", "age": 22})	}		t.Fatalf("BeginTx error = %v", err)	if err != nil {	tx, err := db.BeginTx()	}		t.Fatalf("Configure error = %v", err)	if err != nil {	}})		{Name: "age", Type: "int", Required: true, Default: int64(0)},		{Name: "username", Type: "string", Unique: true, Required: true},		{Name: "id", Type: "uuid:v7", PrimaryKey: true, AutoIncrement: true},	err = db.Configure(TableSchema{Columns: []Column{	defer db.Close()	}		t.Fatalf("Open DB error = %v", err)	if err != nil {	db, err := New.DB(database, table)	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(database, table)) })	_ = os.RemoveAll(filepath.Join(database, table))	table := "driver_crud_tx"	database := "demo"func TestDriver_CRUDAndTx(t *testing.T) {)	"github.com/aid297/aid/simpleDB/kernal"	"testing"	"path/filepath"	"os"	"errors"import (