//go:build never
// +build never

package driver





























































}	}		return &DriverError{Code: ErrorCodeInternal, Err: err}	default:		return &DriverError{Code: ErrorCodeReadOnly, Err: err}	case errors.Is(err, kernal.ErrTxReadOnly):		return &DriverError{Code: ErrorCodeClosed, Err: err}	case errors.Is(err, kernal.ErrDatabaseClosed), errors.Is(err, kernal.ErrTxClosed):		return &DriverError{Code: ErrorCodeConflict, Err: err}	case errors.Is(err, kernal.ErrUniqueConflict), errors.Is(err, kernal.ErrPrimaryKeyConflict), errors.Is(err, kernal.ErrTxConflict):		return &DriverError{Code: ErrorCodeNotFound, Err: err}	case errors.Is(err, kernal.ErrKeyNotFound), errors.Is(err, kernal.ErrRelationNotFound):		return &DriverError{Code: ErrorCodeInvalidArgument, Err: err}	case errors.Is(err, kernal.ErrEmptyKey), errors.Is(err, kernal.ErrInvalidSchema), errors.Is(err, kernal.ErrInvalidQueryCondition), errors.Is(err, kernal.ErrBatchEmpty):	switch {	}		return err	if _, ok := err.(*DriverError); ok {	}		return nil	if err == nil {func wrapError(err error) error {}	return e.Err	}		return nil	if e == nil {func (e *DriverError) Unwrap() error {}	return fmt.Sprintf("driver[%s]: %v", e.Code, e.Err)	}		return "driver error"	if e == nil || e.Err == nil {func (e *DriverError) Error() string {}	Err  error	Code ErrorCodetype DriverError struct {)	ErrorCodeInternal        ErrorCode = "internal"	ErrorCodeReadOnly        ErrorCode = "read_only"	ErrorCodeClosed          ErrorCode = "closed"	ErrorCodeConflict        ErrorCode = "conflict"	ErrorCodeNotFound        ErrorCode = "not_found"	ErrorCodeInvalidArgument ErrorCode = "invalid_argument"const (type ErrorCode string)	"github.com/aid297/aid/simpleDB/kernal"	"fmt"	"errors"import (