//go:build never

package sqlapi
package sqlapi

import (
	"fmt"

	"github.com/aid297/aid/simpleDB/driver"















































































































































































}	return ExecResult{Statement: StmtTruncate, Affected: 1}, nil	}		return ExecResult{}, err	if err = db.TruncateTable(); err != nil {	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execTruncate(s TruncateTableStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtDropTable, Affected: 1}, nil	}		return ExecResult{}, err	if err = db.DropTable(); err != nil {	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execDrop(s DropTableStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtSelect, Rows: rows, Affected: len(rows)}, nil	}		return ExecResult{}, err	if err != nil {	rows, err := db.Find(s.Conditions...)	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execSelect(s SelectStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtDelete, Affected: count}, nil	}		return ExecResult{}, err	if err != nil {	count, err := db.RemoveByCondition(s.Conditions...)	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execDelete(s DeleteStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtUpdate, Affected: 1, Updated: row}, nil	}		return ExecResult{}, err	if err != nil {	row, err := db.UpdateRow(s.PrimaryKey, s.Updates)	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execUpdate(s UpdateStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtInsert, Affected: 1, Inserted: row}, nil	}		return ExecResult{}, err	if err != nil {	row, err := db.InsertRow(s.Row)	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execInsert(s InsertStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtAlterTable, Affected: 1}, nil	}		return ExecResult{}, err	if err = db.AlterTable(s.Plan); err != nil {	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execAlter(s AlterTableStmt) (ExecResult, error) {}	return ExecResult{Statement: StmtCreateTable, Affected: 1}, nil	}		return ExecResult{}, err	if err = db.CreateTable(s.Schema); err != nil {	defer db.Close()	}		return ExecResult{}, err	if err != nil {	db, err := e.open(s.Table)func (e *Engine) execCreate(s CreateTableStmt) (ExecResult, error) {}	}		return driver.New.DB(e.Database, table)	default:		return kernal.New.DB(e.Database, table)	case BackendKernal:	switch e.Backend {func (e *Engine) open(table string) (tableDB, error) {}	TruncateTable() error	DropTable() error	Find(conditions ...kernal.QueryCondition) ([]kernal.Row, error)	RemoveByCondition(conditions ...kernal.QueryCondition) (int, error)	UpdateRow(primaryKey any, updates kernal.Row) (kernal.Row, error)	InsertRow(values kernal.Row) (kernal.Row, error)	AlterTable(plan kernal.AlterTablePlan) error	CreateTable(schema kernal.TableSchema) error	Close() errortype tableDB interface {}	}		return ExecResult{}, fmt.Errorf("unsupported statement")	default:		return e.execTruncate(s)	case TruncateTableStmt:		return e.execDrop(s)	case DropTableStmt:		return e.execSelect(s)	case SelectStmt:		return e.execDelete(s)	case DeleteStmt:		return e.execUpdate(s)	case UpdateStmt:		return e.execInsert(s)	case InsertStmt:		return e.execAlter(s)	case AlterTableStmt:		return e.execCreate(s)	case CreateTableStmt:	switch s := stmt.(type) {func (e *Engine) ExecuteStatement(stmt Statement) (ExecResult, error) {}	return e.ExecuteStatement(stmt)	}		return ExecResult{}, err	if err != nil {	stmt, err := Parse(sql)func (e *Engine) Execute(sql string) (ExecResult, error) {func (e *Engine) Parse(sql string) (Statement, error) { return Parse(sql) }}	return &Engine{Database: database, Backend: backend}	}		backend = BackendDriver	if backend == "" {func NewEngine(database string, backend Backend) *Engine {}	Backend  Backend	Database stringtype Engine struct {)	BackendKernal Backend = "kernal"	BackendDriver Backend = "driver"const (type Backend string)	"github.com/aid297/aid/simpleDB/kernal"