// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/fileManger/destroy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除文件或目录",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FileDestroyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    },
                    "403": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/fileManager/download": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载成功",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "403": {
                        "description": "下载失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/fileManager/list": {
            "post": {
                "description": "按路径获取当前目录文件/目录列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取文件列表",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FileListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    },
                    "403": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/fileManager/storeFolder": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "创建文件夹",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FileStoreFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    },
                    "403": {
                        "description": "创建文件夹失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/fileManager/upload": {
            "post": {
                "description": "上传单个文件到指定路径",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "application/xml",
                    "application/x-yaml",
                    "application/toml"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传路径",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "上传文件内容",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpModule.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "content": {
                                            "$ref": "#/definitions/response.FileUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "获取上传文件失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/fileManager/zip": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "压缩文件或目录",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FileZipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "压缩成功",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    },
                    "403": {
                        "description": "压缩失败",
                        "schema": {
                            "$ref": "#/definitions/httpModule.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpModule.HTTPResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "content": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "request.FileDestroyRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.FileListRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.FileStoreFolderRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.FileZipRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "response.FileUploadResponse": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "savedAs": {
                    "type": "string"
                },
                "savedPath": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9900",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Aid Web Backend API",
	Description:      "Aid Web Backend API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
