database:
    path: demo_transport
engine:
    persistence:
        windowSeconds: 10
        windowBytes: 10mb
        threshold: 100mb
    security:
        compressAlgorithm: gzip # options: gzip
        encryptAlgorithm: aes  # options: aes
        encryptKey: tca7ioTzttwzoh6Ov6G9SBm7ypOWft3ruCvBm5uf8QQ=        
        # 如果设置了使用加密（encryptAlgorithm），则必须提供加密密钥加密方式如下：
        # 1. 生成 32 字节的 AES 密钥，输出为 base64 格式
        # go run ./simpleDB gen-key -algo aes -len 32 -format base64

        # 2. 指定配置文件路径
        # go run ./simpleDB gen-key -config path/to/my_config.yaml
transport:
    http:
        enabled: true
        address: :18080
        ginMode: release
        route:
            health: /health
            profile: /me
            login: /auth/login
            register: /auth/register
            refresh: /auth/refresh
            logout: /auth/logout
            activate: /auth/activate
            deactivate: /auth/deactivate
            assignRole: /auth/assign-roles
            assignRolePermission: /auth/assign-role-permissions
            initSDBPassword: /auth/init-sdb-password
            sql: /sql/execute
            sqlGrant: /sql/grant
            sqlRevoke: /sql/revoke
            admin: /admin
            report: /reports
        limit:
            enabled: true
            requests: 60
            window: 1m
            noTokenPaths:
                - /auth/login
                - /auth/register
                - /auth/init-sdb-password
                - /health
        initPassword: mSdUvQw1V-AElhbrIkjLIbuo
        tokenTTL: 12h
        tokenSecret: ""
        enableAdminRoute: true
        enableReportRoute: true
