database:
    path: demo_transport
engine:
    persistence:
        windowSeconds: 10
        windowBytes: 10mb
        threshold: 100mb
    security:
        compressAlgorithm: "" # options: gzip
        encryptAlgorithm: ""  # options: aes
        encryptKey: ""        # required if encryptAlgorithm is set
transport:
    http:
        enabled: true
        address: :18080
        ginMode: release
        route:
            health: /health
            profile: /me
            login: /auth/login
            register: /auth/register
            refresh: /auth/refresh
            logout: /auth/logout
            activate: /auth/activate
            deactivate: /auth/deactivate
            assignRole: /auth/assign-roles
            assignRolePermission: /auth/assign-role-permissions
            initSDBPassword: /auth/init-sdb-password
            sql: /sql/execute
            sqlGrant: /sql/grant
            sqlRevoke: /sql/revoke
            admin: /admin
            report: /reports
        limit:
            enabled: true
            requests: 60
            window: 1m
            noTokenPaths:
                - /auth/login
                - /auth/register
                - /auth/init-sdb-password
                - /health
        initPassword: mSdUvQw1V-AElhbrIkjLIbuo
        tokenTTL: 12h
        tokenSecret: ""
        enableAdminRoute: true
        enableReportRoute: true
