package kernal

import "fmt"

var (
	ErrEmptyKey              = fmt.Errorf("%s 读取错误：key 为空", dbLogTitle)
	ErrKeyNotFound           = fmt.Errorf("%s 读取错误：key 对应数据不存在", dbLogTitle)
	ErrKeyDeleted            = fmt.Errorf("%s 读取错误：key 已经被删除", dbLogTitle)
	ErrDatabaseClosed        = fmt.Errorf("%s 读取错误：数据库已经被关闭", dbLogTitle)
	ErrDatabaseLocked        = fmt.Errorf("%s 打开数据库错误：数据库文件已被锁定", dbLogTitle)
	ErrCorruptedRecord       = fmt.Errorf("%s 读取错误：数据记录损坏", dbLogTitle)
	ErrDBPathEmpty           = fmt.Errorf("%s 打开数据库错误：目录为空", dbLogTitle)
	ErrUnkownOperation       = fmt.Errorf("%s 未知操作：", dbLogTitle)
	ErrInitDB                = fmt.Errorf("初始化数据库错误")
	ErrSchemaNotConfigured   = fmt.Errorf("%s 结构错误：表结构尚未配置", dbLogTitle)
	ErrSchemaAlreadyExists   = fmt.Errorf("%s 结构错误：表结构已经存在", dbLogTitle)
	ErrInvalidSchema         = fmt.Errorf("%s 结构错误：表结构无效", dbLogTitle)
	ErrFieldNotDefined       = fmt.Errorf("%s 结构错误：字段未定义", dbLogTitle)
	ErrPrimaryKeyMissing     = fmt.Errorf("%s 写入错误：主键缺失", dbLogTitle)
	ErrPrimaryKeyConflict    = fmt.Errorf("%s 写入错误：主键冲突", dbLogTitle)
	ErrPrimaryKeyImmutable   = fmt.Errorf("%s 更新错误：不允许修改主键", dbLogTitle)
	ErrUniqueConflict        = fmt.Errorf("%s 写入错误：唯一索引冲突", dbLogTitle)
	ErrFieldNotIndexed       = fmt.Errorf("%s 查询错误：字段未建立索引", dbLogTitle)
	ErrUnsupportedFieldType  = fmt.Errorf("%s 结构错误：字段类型不支持", dbLogTitle)
	ErrFieldTypeMismatch     = fmt.Errorf("%s 写入错误：字段类型不匹配", dbLogTitle)
	ErrFieldRequired         = fmt.Errorf("%s 写入错误：字段必填", dbLogTitle)
	ErrFieldNotNullable      = fmt.Errorf("%s 写入错误：字段不允许为 null", dbLogTitle)
	ErrFieldLengthViolation  = fmt.Errorf("%s 写入错误：字段长度不合法", dbLogTitle)
	ErrFieldEnumViolation    = fmt.Errorf("%s 写入错误：字段值不在枚举范围内", dbLogTitle)
	ErrFieldCheckViolation   = fmt.Errorf("%s 写入错误：字段 check 约束失败", dbLogTitle)
	ErrInvalidQueryCondition = fmt.Errorf("%s 查询错误：查询条件无效", dbLogTitle)
	ErrInvalidForeignKey     = fmt.Errorf("%s 结构错误：外键定义无效", dbLogTitle)
	ErrRelationNotFound      = fmt.Errorf("%s 查询错误：关联关系不存在", dbLogTitle)
	ErrCascadeDepthExceeded  = fmt.Errorf("%s 查询错误：级联查询深度超限", dbLogTitle)
	ErrCascadeCycleNotAllow  = fmt.Errorf("%s 查询错误：不允许级联环", dbLogTitle)
	ErrBatchEmpty            = fmt.Errorf("%s 写入错误：批量操作数据为空", dbLogTitle)
	ErrTxConflict            = fmt.Errorf("%s 事务错误：检测到写冲突", dbLogTitle)
	ErrTxClosed              = fmt.Errorf("%s 事务错误：事务已关闭", dbLogTitle)
)
