package kernal

import "strings"

func (*app) AssignRolePermissions(database, roleCode string, permissionCodes []string) error {
	return assignRolePermissions(database, roleCode, permissionCodes)
}

func assignRolePermissions(database, roleCode string, permissionCodes []string) error {
	roleCode = strings.TrimSpace(roleCode)
	cleanPermissionCodes := normalizeRoleCodes(permissionCodes)
	if roleCode == "" || len(cleanPermissionCodes) == 0 {
		return ErrInvalidPermissionAssignment
	}

	if err := ensureSystemTables(database); err != nil {
		return err
	}

	rolesDB, err := newSimpleDB(database, systemTableRoles)
	if err != nil {
		return err
	}
	defer rolesDB.Close()

	roleRow, exists, err := rolesDB.FindOne(QueryCondition{Field: "code", Operator: QueryOpEQ, Value: roleCode})
	if err != nil {
		return err
	}
	if !exists {
		return ErrRoleNotFound
	}
	roleID, roleIDOK := roleRow["id"]
	if !roleIDOK {
		return ErrRoleNotFound
	}

	permissionsDB, err := newSimpleDB(database, systemTablePermissions)
	if err != nil {
		return err
	}
	defer permissionsDB.Close()

	rolePermissionsDB, err := newSimpleDB(database, systemTableRolePermissions)
	if err != nil {
		return err
	}
	defer rolePermissionsDB.Close()

	for _, permissionCode := range cleanPermissionCodes {
		permissionRow, found, findErr := permissionsDB.FindOne(QueryCondition{Field: "code", Operator: QueryOpEQ, Value: permissionCode})
		if findErr != nil {
			return findErr
		}
		if !found {
			permissionRow, findErr = permissionsDB.InsertRow(Row{
				"code":        permissionCode,
				"name":        permissionCode,
				"description": "auto generated by role permission assignment",
			})
			if findErr != nil {
				return findErr
			}
		}

		permissionID, permissionIDOK := permissionRow["id"]
		if !permissionIDOK {
			return ErrInvalidPermissionAssignment
		}

		_, linked, linkErr := rolePermissionsDB.FindOne(
			QueryCondition{Field: "roleId", Operator: QueryOpEQ, Value: roleID},
			QueryCondition{Field: "permissionId", Operator: QueryOpEQ, Value: permissionID},
		)
		if linkErr != nil {
			return linkErr
		}
		if linked {
			continue
		}

		if _, linkErr = rolePermissionsDB.InsertRow(Row{"roleId": roleID, "permissionId": permissionID}); linkErr != nil {
			return linkErr
		}
	}

	return nil
}
